baseURL = 'https://aitsam.co.uk/'
languageCode = 'en-gb'
languageName = "English"
languageDirection = "ltr"
weight = 1
title = 'Aitsam Kamran'
# copyright = "Aitsam Kamran"
theme = 'beautifulhugo'
[[module.imports]]
  path = "github.com/halogenica/beautifulhugo"

[params]
  dateFormat = "8 July 2004"

  description = "Personal website of Aitsam Kamran"

[params.author]
  name = "Aitsam Kamran"
  image = "img/pic2.png"
  headline = "Third Year Undergrad at Newcastle University studying Computer Science"
  bio = "Comp Sci Year 3 NCL"
  links = [
    { github = "https://github.com/aitsamk" },
    { linkedin = "https://www.linkedin.com/in/aitsamkamran/" },
  ]

[caches]
  [caches.images]
    dir = ':cacheDir/images'